# Generated by Django 5.0.1 on 2024-03-21 10:27

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_trainer_number_of_plans_made_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.validate_alpha, accounts.validators.validate_name_length]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[accounts.validators.validate_alpha, accounts.validators.validate_name_length]),
        ),
    ]
