# Generated by Django 5.0.1 on 2024-03-22 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programs', '0010_trainingplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='amount_of_days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
