# Generated by Django 5.0.1 on 2024-03-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programs', '0011_alter_trainingplan_amount_of_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='types',
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ManyToManyField(to='training_programs.typesofexercises'),
        ),
    ]
