# Generated by Django 5.0.1 on 2024-03-28 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programs', '0012_remove_exercise_types_exercise_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='types',
        ),
        migrations.AddField(
            model_name='exercise',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training_programs.typesofexercises'),
        ),
    ]
